
create database olist;

use olist;

-- Exploratory Data Analysis (EDA) & Hypothesis 

-- Total Orders
SELECT COUNT(*) AS total_orders
FROM orders;

-- Total Customers
SELECT COUNT(*) AS total_customers
FROM customers;

-- Total Revenue Generated
SELECT ROUND(SUM(payment_value),2) AS total_revenue
FROM payments;

-- Unique Product Categories
SELECT COUNT(DISTINCT product_category_name)
AS unique_categories
FROM products;

-- Order Status
SELECT order_status, COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;

-- Payment Type
SELECT payment_type, COUNT(*) AS total_usage
FROM payments
GROUP BY payment_type
ORDER BY total_usage DESC;

-- Reviews
SELECT review_score, COUNT(*) AS total_reviews
FROM reviews
GROUP BY review_score
ORDER BY review_score;

-- Top 10 Customer States
SELECT TOP 10 customer_state, COUNT(*) AS customers
FROM customers
GROUP BY customer_state
ORDER BY customers DESC;


-- Monthly Revenue Trends
SELECT YEAR(o.order_purchase_timestamp) AS year, MONTH(o.order_purchase_timestamp) AS month, ROUND(SUM(p.payment_value),2) AS revenue
FROM orders o
JOIN payments p ON o.order_id = p.order_id
GROUP BY YEAR(o.order_purchase_timestamp), MONTH(o.order_purchase_timestamp)
ORDER BY year, month;

-- Top Product Categories by Revenue
SELECT TOP 10 pr.product_category_name, ROUND(SUM(oi.price),2) AS revenue, COUNT(*) AS total_sales
FROM order_items oi
JOIN products pr ON oi.product_id = pr.product_id
GROUP BY pr.product_category_name
ORDER BY revenue DESC;

-- Average Delivery Time
SELECT AVG(DATEDIFF(DAY, order_purchase_timestamp, order_delivered_customer_date)) AS avg_delivery_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;

-- Top Sellers by Revenue
SELECT TOP 10 seller_id, ROUND(SUM(price),2) AS revenue
FROM order_items
GROUP BY seller_id
ORDER BY revenue DESC;

-- Revenue generated by each Customer State
SELECT c.customer_state, ROUND(SUM(p.payment_value),2) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments p ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC;

-- Delayed Orders
SELECT COUNT(*) AS delayed_orders
FROM orders
WHERE order_delivered_customer_date > order_estimated_delivery_date;\

-- Product Categories with Lowest Reviews
SELECT DISTINCT pr.product_category_name, ROUND(AVG(r.review_score),2) AS avg_review_score
FROM products pr
JOIN order_items oi ON pr.product_id = oi.product_id
JOIN reviews r ON oi.order_id = r.order_id
GROUP BY pr.product_category_name
ORDER BY avg_review_score ASC;

-- Revenue Growth 
WITH monthly_revenue AS (
SELECT YEAR(o.order_purchase_timestamp) AS year, 
MONTH(o.order_purchase_timestamp) AS month,
SUM(p.payment_value) AS revenue
FROM orders o
JOIN payments p ON o.order_id = p.order_id
GROUP BY YEAR(o.order_purchase_timestamp), MONTH(o.order_purchase_timestamp))
SELECT year, month, revenue,
LAG(revenue) OVER (ORDER BY year, month) AS previous_month, ROUND((revenue - LAG(revenue) OVER (ORDER BY year, month)) * 100.0 /
LAG(revenue) OVER (ORDER BY year, month),2) AS growth_percentage
FROM monthly_revenue;

-- Seller Ranking
SELECT TOP 20 order_id, price, freight_value, ROUND(freight_value * 100.0 / price,2) AS freight_percentage
FROM order_items
ORDER BY freight_percentage DESC;

-- Customer Lifetime Value (CLV)
SELECT TOP 20 c.customer_unique_id, COUNT(DISTINCT o.order_id) AS total_orders, ROUND(SUM(p.payment_value),2) AS customer_lifetime_value
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments p ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY customer_lifetime_value DESC;

-- Review by Freight Percentage
SELECT TOP 50  oi.order_id, oi.price, oi.freight_value, ROUND((oi.freight_value * 100.0 / oi.price), 2) AS freight_percentage, r.review_score, p.product_category_name
FROM order_items oi
JOIN reviews r ON oi.order_id = r.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE oi.freight_value > 50 AND r.review_score >= 4
ORDER BY oi.freight_value DESC;
